#!/usr/bin/env python3
"""perf_study.py - micro-architecture design-space exploration.

Builds the SoC simulator in several configurations (Verilog parameters),
runs CoreMark and Dhrystone on each, and writes docs/perf_results.md.

    python3 scripts/perf_study.py
"""
import os
import re
import subprocess
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
BUILD = os.path.join(ROOT, 'build')

# name, Verilog parameter overrides, description
CONFIGS = [
    ('baseline',     {},                                             'BP on, 2x4 KiB caches, 1-cycle BRAM'),
    ('no_bp',        {'ENABLE_BP': 0},                               'branch prediction disabled (predict not-taken)'),
    ('dram10',       {'RAM_LATENCY': 10},                            'baseline + 10-cycle main memory'),
    ('dram10_nocache', {'RAM_LATENCY': 10, 'ICACHE': 0, 'DCACHE': 0}, '10-cycle memory, no caches'),
    ('dram10_1k',    {'RAM_LATENCY': 10, 'CACHE_SET_BITS': 5},       '10-cycle memory, 1 KiB caches'),
    ('dram10_16k',   {'RAM_LATENCY': 10, 'CACHE_SET_BITS': 9},       '10-cycle memory, 16 KiB caches'),
    ('big_bp',       {'BTB_BITS': 8, 'BHT_BITS': 12},                '256-entry BTB, 4096-entry gshare'),
]
BENCH = ['coremark', 'dhrystone']


def sh(cmd, **kw):
    return subprocess.run(cmd, shell=True, cwd=ROOT, text=True, capture_output=True, **kw)


def build(name, params):
    defs = ' '.join(f'-G{k}={v}' for k, v in params.items())
    r = sh(f'make sim-soc SOC_TAG=_perf_{name} SOC_DEFS="{defs}"')
    if r.returncode:
        print(r.stdout[-2000:], r.stderr[-2000:])
        sys.exit(1)
    return os.path.join(BUILD, f'sim_soc_perf_{name}', 'Vrv_soc')


def run(sim, bench):
    elf = os.path.join(BUILD, 'sw', f'{bench}.elf')
    stats = os.path.join(BUILD, f'perf_{os.path.basename(os.path.dirname(sim))}_{bench}.txt')
    r = sh(f'{sim} +elf={elf} +stats={stats} +max_cycles=100000000')
    out = r.stdout
    s = dict(l.strip().split('=') for l in open(stats) if '=' in l)
    s = {k: int(v) for k, v in s.items()}
    if bench == 'coremark':
        ticks = int(re.search(r'Total ticks\s*:\s*(\d+)', out).group(1))
        iters = int(re.search(r'Iterations\s*:\s*(\d+)', out).group(1))
        ok = all(x in out for x in ('crclist       : 0xe714', 'crcmatrix     : 0x1fd7', 'crcstate      : 0x8e3a'))
        s['score'] = iters / (ticks / 1e6)          # CoreMark / MHz
        s['valid'] = ok
    else:
        m = re.search(r'STATS cycles=(\d+) instret=(\d+) runs=(\d+)', out)
        cyc, runs = int(m.group(1)), int(m.group(3))
        s['score'] = 1e6 / (cyc / runs) / 1757.0    # DMIPS / MHz
        s['valid'] = 'should be:   DHRYSTONE PROGRAM, SOME STRING' in out
    return s


def main():
    r = sh('make -C sw coremark dhrystone')
    if r.returncode:
        print(r.stderr)
        sys.exit(1)
    rows = []
    for name, params, desc in CONFIGS:
        print(f'[{name}] building...', flush=True)
        sim = build(name, params)
        res = {b: run(sim, b) for b in BENCH}
        rows.append((name, desc, res))
        cm, dh = res['coremark'], res['dhrystone']
        print(f'   CoreMark/MHz={cm["score"]:.3f} IPC={cm["instret"]/cm["cycles"]:.3f}  '
              f'DMIPS/MHz={dh["score"]:.3f}', flush=True)

    with open(os.path.join(ROOT, 'docs', 'perf_results.md'), 'w') as f:
        f.write('# Performance Results (generated by scripts/perf_study.py)\n\n')
        f.write('CoreMark: 2K performance run, 20 iterations, `-O3 -funroll-loops`; scores are per MHz '
                'from cycle counts (simulation, so the 10-second rule does not apply).\n'
                'Dhrystone 2.2 (riscv-tests build, `-O2 -fno-inline`), 2000 runs.\n\n')
        f.write('| Config | Description | CoreMark/MHz | CM IPC | DMIPS/MHz | DS IPC | Branch MPKI (CM) '
                '| Mispredict rate (CM) | I$ misses (CM) | D$ misses (CM) |\n')
        f.write('|---|---|---|---|---|---|---|---|---|---|\n')
        for name, desc, res in rows:
            cm, dh = res['coremark'], res['dhrystone']
            mpki = 1000.0 * cm['mispredict'] / cm['instret']
            rate = 100.0 * cm['mispredict'] / max(1, cm['ctrl'])
            f.write(f"| {name} | {desc} | {cm['score']:.2f}{'' if cm['valid'] else ' (INVALID)'} | "
                    f"{cm['instret']/cm['cycles']:.3f} | {dh['score']:.2f}{'' if dh['valid'] else ' (INVALID)'} | "
                    f"{dh['instret']/dh['cycles']:.3f} | {mpki:.1f} | {rate:.1f}% | {cm['icache_miss']} | "
                    f"{cm['dcache_miss']} |\n")
    print('wrote docs/perf_results.md')


if __name__ == '__main__':
    main()
